/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ThreadInfo {
  name: string
  cpuUsage: number
  frequency: number
  vendorId: string
  brand: string
}
export interface CpuInfo {
  name: string
  cpuUsage: number
  frequency: number
  vendorId: string
  brand: string
  physicalCoreCount: number
  threads: Array<ThreadInfo>
}
export function cpuInfo(): CpuInfo
export interface DiskInfo {
  name: string
  totalSpace: string
  availableSpace: string
  isRemovable: boolean
  type: string
}
export function disksInfo(): Array<DiskInfo>
export interface NetworkInfo {
  name: string
  received: number
  totalReceived: number
  transmitted: number
  totalTransmitted: number
  packetsReceived: number
  packetsTransmitted: number
  totalPacketsTransmitted: number
  errorsOnReceived: number
  totalErrorsOnReceived: number
  errorsOnTransmitted: number
  totalErrorsOnTransmitted: number
}
export function networksInfo(): Array<NetworkInfo>
export interface LoadAverageInfo {
  1: number
  five: number
  fifteen: number
}
export function loadAverageInfo(): LoadAverageInfo
export interface MemoryInfo {
  totalMemory: string
  availableMemory: string
  usedMemory: string
  freeMemory: string
  totalSwap: string
  freeSwap: string
  usedSwap: string
}
export function memoryInfo(): MemoryInfo
export interface OsInfo {
  name: string
  kernelVersion: string
  osVersion: string
  hostName: string
}
export function osInfo(): OsInfo
export interface ProcessInfo {
  name: string
  cmd: string
  path: string
  pid: number
  ppid: number
  envVar: Array<string>
  cwd: string
  root: string
  memory: number
  virtualMemory: number
  runningTime: number
  status: string
  diskUsage: DiskUsage
  cpuUsage: number
}
export interface DiskUsage {
  readBytes: number
  writtenBytes: number
  totalReadBytes: number
  totalWrittenBytes: number
}
export function processesInfo(): Array<ProcessInfo>
export interface BatteryInfo {
  vendor: string
  model: string
  state: string
  temperature: string
  cycleCount: number
  energyFullDesign: string
  energyFull: string
  energy: string
  energyRate: string
  voltage: string
  stateOfCharge: string
  stateOfHealth: string
}
export function batteryInfo(): Array<BatteryInfo>
export interface GraphicsInfo {
  brand: string
  name: string
  fanSpeed: string
  powerLimit: string
  memory: GpuMemory
  temperature: string
  utilization: GpuUsage
}
export interface GpuMemory {
  total: string
  free: string
  used: string
}
export interface GpuUsage {
  gpu: string
  memory: string
}
export function graphicsInfo(): Array<GraphicsInfo>
export interface ComponentInfo {
  label: string
  temperature: string
}
export function componentsInfo(): Array<ComponentInfo>
